const collegeOptions = [
  "A E T College, Doddakannelli Village, Carmelaram Post",
  "AASHLAR BUSINESS SCHOOL",
  "ADARSHA COLLEGE OF ENGINEERING",
  "AE & CS Pavan College of Physical Education",
  "AE & CS Ramapriya College of Education, Bangalore -Chennai Bye pass Rd",
  "AMBITION INSTITUTE OF TECHNOLOGY",
  "AMRUT INSTITUTE JUNAGADH",
  "ASANSOL ENGINEERING COLLEGE",
  "ASWATHAIAH ESTHURI SANJEEVAMMA NATIONAL DEGREE COLLEGE",
  "Aadya Aviation College, Kammanahalli, HRBR layout, Kalyannagar",
  "Acharya Women’s First Grade College",
  "Adarsha College of Management Studies, P.C Halli",
  "Adarsha College, K.R. Puram",
  "Advitya Degree College",
  "Akshaya College, Kavalbyrasandra New Extn, RT Nagar",
  "Al-Ameen Dr. MomthazAhamed Khan College",
  "Al-Mighty First Grade College, Nagavara Main Road",
  "Al-Mighty First Grade Evening College, Nagavara Main Raod",
  "Alpha Degree College",
  "Amarajyothi Degree College",
  "Anjanadri Degree College, SN Plaza, Bychapura Road",
  "Anjanadri First Grade College, Paresandra Cross",
  "Army Institute of Fashion & Design, Nagareshwaranagehalli, Kottannur Post",
  "Army Institute of Hotel Management & Catering, Nagareshwaranagehalli, Kottannur Post",
  "Asian Institute of Gaming and Animation, HAL Airport Road",
  "B E T College of Management and Science, Dodda Banasawadi",
  "B. S. PATEL POLYTECHNIC",
  "BGS College of Commerce",
  "BGS Institute of Management Studies, BGS Campus",
  "BGS Science Academy, Agalagerki",
  "BHILAI INSTITUTE OF TECHNOLOGY",
  "BHILAI INSTITUTE OF TECHNOLOGY, RAIPUR.",
  "BITT POLYTECHNIC",
  "BM COLLEGE OF MANAGEMENT & RESEARCH.",
  "BM COLLEGE OF TECHNOLOGY",
  "BUDGE BUDGE INSTITUTE OF TECHNOLOGY",
  "Bangalore Animation College, HAL 3rd Stage, Jeevanbimanagar",
  "Bangalore City College of Education, Kalyananagar",
  "Bangalore City College, Banasawadi, Kalayananagar Post",
  "Bangalore School of Design, K. Narayanapura, Kothunur Post",
  "Basavashree Institute of Management Studies",
  "Bengaluru College of Management Studies, Kothunur Post",
  "Bengaluru Institute of Management and Science, Bendaganahalli Village, Huskur, Mandar Post",
  "Best Degree College, Near CSI Hospital",
  "Blooms First Grade College, Karkur",
  "Blue Moon First Grade College",
  "CHH. SHIVAJI POLYTECHNIC,VADUJ",
  "CMR Centre for Business Studies, Bhuvanagiri, OMBR Layout",
  "COLLEGE OF ENGINEERING BHUBANESWAR",
  "CRR Degree College",
  "Cambridge College Basavanapura Main Road , K.R Puram",
  "Cavalier Animation & Media College, I Block HRBR Layout, Kalyannagar, Banasawadi",
  "Chaithanya Institute of Management and Science, Bangarpet Road",
  "Challa College of Commerce, Ramamurthy Nagar Main Road",
  "Chinmaya Institute of Management, Indiranagar",
  "Chinnamma  Junjappa Reddy R.J.S College,  Maratthahalli",
  "Christ  College of Science & Management, Almbady",
  "Christ The King College, Kowdenahalli",
  "Christian Institute of Management, Horamavu, Hennur Main Road",
  "Constituent College of University, Bengaluru North University, Lingarajapuram",
  "DIVYA COLLEGE OF PHARMACY",
  "DNYANSADHANA INSTITUTE OF PHARMACY",
  "DON BOSCO College, Bosco Nagar, TC Palya, K R Puram",
  "Deccan College of Management and  Science, Kannur Village, Baguluru Main Road, Bidaralli Hobli",
  "Diamond College of Management and Science, T.C. Palya, K.R. Puram",
  "Dolphin's Degree College",
  "Dr Sri Jachani Rastriya Vidyapeeta, Vapasandra",
  "Dr. S.R. Chandrashekar Institute of Speech and Hearing, Hennur Road",
  "Dr. Thimmaiah College of Degree and Management Studies, Oorgam",
  "East point College of  management, HRBR Layout, Kalyananagar",
  "EbenEzer Degree College, Ebenezer Nagar, Kothanur Post",
  "Excellent Degree College",
  "Faran College of Management, Kannur Village & Post, Bagalur Main Raod",
  "G. M. VEDAK INSTITUTE OF TECHNOLOGY",
  "GOVERNMENT POLYTECHNIC,BEED",
  "GRAMIN COLLGE OF ENGIEERING",
  "GRAMIN POLYTECHNIC",
  "GURU GOBIND SINGH POLYTECHNIC, NASHIK",
  "GURUNANAK INSTITUTE OF TECHNOLOGY",
  "Gear B.Ed College, Doddakanelli",
  "Global College of Management Studies, Pillagumpe",
  "Global Evening College, Bendaganahalli, Old Madras Road",
  "Global School of Counselling,  Hennur-Baglur Road,  Kothannuru",
  "Gnanadri First Grade College, Srinivasapura",
  "Goodwill Christian College for Women, Frezer Town",
  "Gopalan College of Commerce, Hoodi Village, K.R. Puram",
  "Government First Grade College",
  "Government First Grade College for Boys",
  "Government First Grade College for Women",
  "Grace  International College, Hidayath Nagar, KG Halli",
  "Green City Degree College, Kurandahalli, Hosur-Malur Main Road",
  "Green Mountain College, HAL 2nd Stage, New Thippasandra Main Road",
  "HALDIA INSTITUTE OF TECHNOLOGY",
  "HKBK Degree College, Nagawara",
  "HKBK E-Degree College, Nagawara",
  "HUDA National Degree College for Arts, Commerce & Science, D J Halli main Road, Pulikeshinagar",
  "Hasnath College, Hennur Bande, Kalyannagar",
  "Hindustan Business School, K.R. Puram",
  "I A School of Management Studies, Hennur Cross, Kalyannagar",
  "IBM Degree College",
  "IES COLLEGE OF TECHNOLOGY, BHOPAL",
  "IES INSTITUTE OF PHARMACY",
  "INDO-GERMAN TOOL ROOM,INDORE",
  "INDOTECH COLLEGE OF ENGINEERING",
  "ISBC College of Arts, Science and Commerce, Doddanekundi Cross",
  "ITM POLYTECHNIC",
  "Indian Academy Degree College, Hennur Cross, Hennur Main Road, Kalyan Nagar",
  "Indian Academy Evening College, Hennur Cross, Kalyannagar",
  "Indiranagar Evening College, Indiranagar",
  "Indo Asian Academy Degree College, HRBR Layout, 2nd Block, Kalyannagar",
  "Indo Asian Women’s Degree College, Kalyananagar",
  "Indus Valley Degree College, Basavanapura Main Road, Gayatri Layout, K.R. Puram",
  "Infant Jesus Evening College, Lingarajapuram",
  "Innova Institute of Management and Science, Subbannapalya, Kalyannagar",
  "Inspire Institute of Science and Commerce",
  "International Institute of Business Management, Chintamani Road",
  "JIS COLLEGE OF ENGINEERING",
  "JIS SCHOOL OF POLYTECHNIC",
  "JSS ACADEMY OF TECHNICAL EDUCATION",
  "Jesse Degree College, TC Palya Main Road, Rammurthy Nagar",
  "Jnanaganga Degree College",
  "KANPUR INSTITUTE OF TECHNOLOGY",
  "KASHI INSTITUTE OF PHARMACY",
  "KASHI INSTITUTE OF TECHNOLOGY",
  "KESHAV POLYTECHNIC",
  "KRISHNA ENGINEERING COLLEGE",
  "KVN Degree College, Varadenahalli, MalurTaluk",
  "KairaleeNiketan Golden Jubilee Degree College, Indirangar",
  "Kanakasri  First Grade College",
  "Khyathi Degree College",
  "Kingston Academy Degree College",
  "Koshys Institute of Management Studies, Kadusonnappanahalli",
  "Kristu Jayanti College, Autonomous, K. Narayaanapura",
  "Krupanidhi Degree College, Chikkabellandur, VarthoorHobli",
  "Krupanidhi Group of Institutions, Chikkabellandur, VarthoorHobli",
  "L.B.S Government First Grade College, Dinnoor Road, Jayamahal Extn.",
  "LOTUS BUSINESS SCHOOL",
  "Lady Vailankanni Degree College, Varthur",
  "Lavanya College of Education",
  "Lavanya Degree College",
  "Lohit's Academy of Commerce, Horamavu, Kalkere Main Road",
  "Lourdes College of Education, BabusaPalya",
  "Lowry Adventist College, Dooravani Nagar",
  "M J COLLEGE",
  "MARATHWADA INSTITUTE OF TECHNOLOGY",
  "MEERUT INSTITUTE OF TECHNOLOGY",
  "MEGHNAD SAHA INSTITUTE OF TECHNOLOGY",
  "MILLENNIUM INSTITUTE OF TECHNOLOGY",
  "MITTAL INSTITUTE OF TECHNOLOGY",
  "MM COLLEGE OF TECHNOLOGY",
  "MORADABAD INSTITUTE OF TECHNOLOGY",
  "MVJ College of Education, Marathahalli",
  "Mahadeva College Of Commerce",
  "Maheshwari  Institute of Management & Science, New Bus Stand",
  "Mahilasamaj Arts, Science & Commerce Management Studies College",
  "Malva Evening College Of Arts Commerce Yogic Science",
  "Manasa B.Ed. College, Araleri Main Road, White Garden",
  "Manasa Institute of Science & Management Studies",
  "Millat Women's College, Millat Nagar",
  "Miranda College of Education",
  "Montfort College, Indira Nagar",
  "Mother Theresa Degree College",
  "N B C Degree College, Doddagubbi, Byrathi",
  "NARULA INSTITUTE OF TECHNOLOGY",
  "NETAJI SUBHASH ENGINEERING COLLEGE",
  "NORTH INDIA INSTITUTE OF TECHNOLOGY",
  "Nagarjuna College of Management Studies, Chikmarali Village",
  "Nalanda College of Education",
  "Nalanda College of Higher Education, Boodigere",
  "National First Grade College",
  "Navachetana Degree College",
  "New Baldwin International Degree College, Budigere Cross, Mandur Post, Virgonagar",
  "New Horizon College, Kadubisanahalli",
  "New Horizon College, Kasturinagar, NGEF Layout",
  "New Shores International College, Banaswadi",
  "Nisarga Degree College, Ettakodi",
  "OAKBROOK BUSINESS SCHOOL (MBA)",
  "OMDAYAL GROUP OF INSTITUITIONS",
  "ORIENTAL COLLEGE OF PHARMACY",
  "ORIENTAL COLLEGE OF TECHNOLOGY",
  "One School of Business, Nagawara",
  "P.E.S. COLLEGE OF ENGINEERING",
  "PRAVARA RURAL COLLEGE OF PHARMACY",
  "PRAVARA RURAL ENGINEERING COLLEGE",
  "Patel Institute of Science & Management,   Belandur Post",
  "Pragathi College of Education, M.G. Road",
  "Pragathi Degree College, Kadugodi",
  "Pragathi First Grade College",
  "Pragathi Science & Management Studies",
  "Prakruthi Degree College",
  "Preethi College of Management and Science",
  "Province College, HBR Layout, 80ft Road, Near Hennur Bus Stop",
  "R K Vision Degree College",
  "R.C.PATEL INSITUTE OF PHARMACY",
  "RADHARAMAN ENGINEERING COLLEGE",
  "RAJ KUMAR GOEL INSTITUE OF TECHNOLOGY",
  "Rajadhani College, Mahadevapura Post, White Filed Main Road",
  "Ravi College of Education, Gowripet",
  "Ravi College, Gowripet",
  "Ray Integrated College, HBR Layout",
  "Regional College Of Management, Mudugurki",
  "Rock Valley College of Science & Management",
  "Rock Valley Teachers College",
  "Royal College of Management Studies, Hennur Ring Road Junction",
  "Royal Degree College",
  "S M Visvesvaraya Degree College, Alappanahalli",
  "SACHDEVA INSTITUTE OF TECHNOLOGY",
  "SACHDEVA POLYTECHNIC",
  "SAMRAT ASHOK TECHNOLOGICAL INSTITUTE",
  "SAM’s College of Management Studies, Murgesh Mudaliyar Road, Fazer Town",
  "SANJIVANI K.B.P.POLYTECHNIC,KOPARGAON",
  "SANT TUKARAM POLYTECHNIC",
  "SAROJ MOHAN INSTITUTE OF TECHNOLOGY",
  "SAROJINI INSTITUTE OF TECHNOLOGY",
  "SC/ST Residential Government First Grade College",
  "SCOPE COLLEGE OF ENGINEERING, BHOPAL",
  "SCT College of Education, Vignananagar, Kaggadasapura Main Road, Thippasandra",
  "SCT Degree College, Mudigere Gate",
  "SEA College of  Arts, Science & Commerce, Ekta Nagar, Basavanapura, Virgonagar Post",
  "SEA College of Education, Ekta Nagar, Basavanapura, Virgonagar Post",
  "SEA Evening Degree College, Ektanagar, Basavanaupra, Virgonagar Post",
  "SHRI BHERULAL PHARMACY INSTITUTE",
  "SHRI RAM COLLEGE OF MANAGEMENT",
  "SHRI RAM GROUP OF COLLEGES",
  "SHRI RAM POLYTECHNIC",
  "SILIGURI INSTITUTE OF TECHNOLOGY",
  "SILIGURI INSTITUTE OF TECHNOLOGY(HMCT)",
  "SILIGURI INSTITUTE OF TECHNOLOGY(MCA)",
  "SJES College of Education,  Medahalli, Old Madras Road",
  "SJES College of Management Sudies, Medahalli",
  "SMT. VIDYAWATI COLLEGE OF PHARMACY",
  "SOPHITORIUM ENGINEERING COLLEGE",
  "SOPHITORIUM MANAGEMENT COLLEGE",
  "SRUSHTI College, Karthik Nagar, Marathahalli Outer Ring Road",
  "SSR College of Science & Management Studies, Kylasanahalli, KR Puram Hobli",
  "SSR College of Science and  Management Studies, Kothannur Post",
  "SUBHASH INSTITUTE OF TECHNOLOGY",
  "SYNERGY INSTITUTE OF TECHNOLOGY",
  "SYNERGY POLYTECHNIC, BHUBANESWAR",
  "Sacred Heart Degree College for Women, Jeevanbheemanagar",
  "Sahyadri Degree College, Tekal Road",
  "Sahyadri First Grade College",
  "Sai Vijaya First Grade College, Kollur Road",
  "Sambhram College of Hotel Management",
  "Samrat Degree  College",
  "Samruddi Degree College",
  "Sapthagiri First Grade College, Gundamanatha Village",
  "Sharada College of Education",
  "Sharada Women’s First Grade College",
  "Silicon City College, Ravindra Layout, KR Puram, Basavanapura Road",
  "Sir  M. Vishveshwaraiah First Grade College, H.A.L ",
  "Smart Degree College",
  "Smt. Danamma Channabasavaiah College of Arts, Commerce and Science & Management  Studies, Kolar-Mulabagil Road",
  "Smt. Danamma Channabasavaiah College of Arts, Commerce, Science & Management Studies",
  "Smt. Danamma Channabasavaiah College of Arts, Science, Commerce & Management",
  "Smt. Ramamani Sundararaja Iyengar (SRSI) First Grade College, Bellur Village",
  "Sophia Degree College, Shampur Road, Ashok Nagar, KG Halli",
  "Sree Adithya Degree College, TG Extension",
  "Sri BaghawanMahaveer Jain Degree College",
  "Sri BalagangadharanathaSwamiji School of Business Management, Byrapalli",
  "Sri Bapuji College of Education",
  "Sri Cauvery  Degree College, Kodihalli, HAL 2nd Stage",
  "Sri Devaraj Urs Institute of Management",
  "Sri Devaraja Urs First Grade Evening  College",
  "Sri Dharmaguru B.Ed. College",
  "Sri Dutta Sai Rural Degree College, KGF Road, Bethamangala, KGF(T)",
  "Sri Gokula College of Arts, Science & Management Studies",
  "Sri Govindatheertha College, Nandi",
  "Sri Hemadri B.Ed. College,Arekalalli post",
  "Sri Jagadguru Balagangadaranatha Swamy College of Physical Education",
  "Sri K Venkatapatheppa College of Education, K V Campus",
  "Sri K Venkatapatheppa College of Physical Education, K V Campus",
  "Sri Kongadiayappa College",
  "Sri Kongadiyappa College of Education",
  "Sri Krishna College of Education",
  "Sri Krishna Degree College",
  "Sri Krishna Rukmini First Grade College",
  "Sri Mangilal Sundar Bai Gotawat Jain College of Arts & Commerce, Indiranagar 2nd stage",
  "Sri Maruthi Degree College",
  "Sri Surya First Grade College",
  "Sri Vani Degree College",
  "Sri Vardhaman Mahaveer Jain Evening College, 2nd Stage, Indiranagar",
  "Sri Venkat First Grade Evening College, Kammanahalli, Subbannapalya",
  "Sri Venkateshwara College of Science & Management Studies, K.R. Puram",
  "Sri Vidyavikas Degree College, Sonnashettihalli",
  "Sri Vijayendra B.Ed. College, Oorgaumpet",
  "Sri Vishwa Viveka First Grade College, Vapasandra",
  "Sri Vivekananda Degree College",
  "St. Aloysius Degree College, St. Aloysius PU Campus, Cox Town",
  "St. George College of Management and Science, Sarvajna Nagara, Banasawadi, OMBR Layout",
  "St. Hopkins International College, HRBR Layout, Kalyannagar",
  "St. Jerome's Degree College, Ambedkarnagar, Malur-Sarjapur Road, Carmelaram",
  "St. Vincent Pallotti College, Kalyannagar Post",
  "St. Xavier Degree College, HBR Layout, HBR 4th Block",
  "St. Xavier’s Degree Evening College, Nagawara",
  "St.Anns Women’s College, Ramamurthynagar",
  "Suguna B.Ed. College,Tamaka",
  "Swamy Vivekananda First Grade College",
  "TECHNO ENGINEERING COLLEGE BANIPUR",
  "TECHNO INTERNATIONAL BATANAGAR",
  "TECHNO INTERNATIONAL NEW TOWN",
  "TECHNO MAIN POLYTECHNIC SALT LAKE",
  "TECHNO MAIN SALT LAKE",
  "Teachers Academy Degree College, Hennur Main Road",
  "Teachers Academy Evening Degree College, Hennur Main Road",
  "The East Point College of  Higher Education, Bidarahalli, Virgonagar Post",
  "The Golden Gleams First Grade College, M.G. Road",
  "U. V. PATEL COLLEGE OF ENGINEERING",
  "US Business School, Frazer Town",
  "United Degree College, Pillanna Garden, Nagawara Main Road",
  "United International Degree College",
  "University College of Education",
  "VBR Degree College, HBR Layout, Hennur",
  "VIDARBHA INSTITUTE OF TECHNOLOGY",
  "VIDYA COLLEGE OF ENGINEERING",
  "VISHVESHWARYA GROUP OF INSTITUTIONS",
  "VNS GROUP OF INSTITUTIONS",
  "Venkatadri  Degree College, Near Railway Station",
  "Vidyalaya Evening College",
  "Vidyanidhi Institute of Commerce and Management Studies",
  "Vidyanikethan College, Chintamani",
  "Vidyapana Degree College",
  "Vijaya First Grade College",
  "Vijaya Vittala Institute of Management and Science, Hennur-Bagaluru Road",
  "Vijayadri Degree College",
  "Vikas First Grade College",
  "Vikram College of Education, Chelur Road",
  "Vishnu B.Ed. College, Hunasanahalli",
  "Vishnupriya College of Management",
  "Vision Degree College, Banaswadi",
  "YASHODA TECHNICAL CAMPUS SATARA",
];

export default collegeOptions;