const collegeOptions = [
  "Acharya B School",
  "Acharya Polytechnic",
  "Acharya Institute of Technology",
  "Acharya Institute of Graduate Studies",
  "Acharya Institute of Management and Sciences",
  "Acharya Pathashala Rural College of Engineering",
  "Acharyas NRV School of Architecture (Soladeva",
  "Achutha Institute of Technology",
  "ACS College of Engineering",
  "Aditya Academy of Architecture & Design",
  "Alliance University",
  "Alliance College of engineering and design (Chik",
  "Alpha College of Engineering",
  "AMC College of Engineering",
  "Amrita School of Engineering",
  "Amrutha Institute of Engineering & Management",
  "Atria Institute of Technology",
  "Bangalore University",
  "Bangalore College of Engineering & Tech",
  "Bangalore City College",
  "Bangalore Institute of Technology",
  "Bangalore Management Academy",
  "Bangalore Technological Institute",
  "BES Institute of Technology",
  "BMS College of Architecture",
  "BMS College of Engineering",
  "BMS Institute of Technology",
  "BMS School of Architecture",
  "BNM Institute of Technology",
  "Brindavan College",
  "Brindavan College of Engineering",
  "BSF Institute of Technology",
  "BTL Institute of Technology Management",
  "Cambridge Institute of Technology",
  "Cambridge Institute of Technology (North Campus)",
  "Cavaliar College",
  "CES Institute of Fashion Technology",
  "Chris Canadian",
  "Christ University",
  "Christ University, Pune",
  "Christ University, Yeswanthpur Campus",
  "Christ (Deemed to be University) Central campus",
  "Christ (Deemed to be University) Lavasa, Pune",
  "Christ Deemed to be University (Kengeri)",
  "City Engineering College",
  "CMR University",
  "CMR institute of Technology",
  "CMR University OMBR Campus",
  "CMR Degree College, OMBR Layout",
  "Dayananda Sagar Academy of Technology & Ma",
  "Dayananda Sagar College of Engineering",
  "Dayananda Sagar College of Arts, Science, and Commerce",
  "Dayananda Sagar Institute of Technology",
  "Don Bosco College",
  "Don Bosco Institute of Technology",
  "Dr Ambedkar Institute of Technology",
  "Dr Sri Sri Sri Shivakumara Mahaswamy College",
  "East Point College",
  "East Point College of Engineering & Technology",
  "East Point College of Engineering for Women",
  "East West College of Engineering",
  "East West Institute of Technology",
  "East West Polytechnic",
  "Ebenezer College",
  "Garden City University",
  "Ghousia College of Engineering",
  "Global Academy of Technology",
  "Gopalan College of Engineering & Management",
  "Gopalan School of Architecture & Planning",
  "Government Engineering College (Ramanagara)",
  "Government SKSJ Technological Institute (K R",
  "Goodwill College",
  "Goodwill Christian College for Women",
  "HKBK College of Engineering",
  "IIBS Bangalore, R.T. Nagar Campus",
  "Indira Gandhi Institute of Technology",
  "Indo Asian College",
  "International Institute of Information Technology, Bangalore (IIITB)",
  "Impact College of Engg & Applied Science",
  "Impact School of Architecture",
  "Indian Academy",
  "Indian Academy School of Management Studies",
  "Indian Institute of Science (IISc)",
  "Islamia Niswan Degree College for Women",
  "Islamiah Institute of Technology",
  "Jain University",
  "Jain University (Jakkasandra)",
  "Jain University Jayanagar",
  "Jnana Vikas Institute of Technology",
  "JSS Academy of Technical Education",
  "Jyoti Nivas",
  "Jyothy Institute of Technology",
  "Kempegowda College of Engineering",
  "Kengeri College",
  "KLE College of Engineering",
  "KLE Technological University",
  "Koshys College",
  "KNS Institute of Technology",
  "KS Institute of Technology",
  "KS School of Engineering and Management (KS",
  "MN Technology Institutute",
  "Mangalore Institute of Fire & Safety Engineering",
  "Malleswaram Ladies' Association Academy of Higher Learning",
  "Mount Carmel College",
  "MS Engineering College",
  "MS Ramaiah Institute of Technology",
  "M S Ramaiah Institute of Technology",
  "M.S. Ramaiah College of Arts, Science, and Commerce",
  "MVJ College of Engineering",
  "Nadgir Institute of Engineering & Technology",
  "Nagarjuna Degree College",
  "National Institute of Technology Karnataka (NITK), Surathkal",
  "NBC College",
  "New Horizon College, Kasthuri Nagar",
  "Nitte Meenakshi Institute of Technology",
  "Nagarjuna College of Engineering & Technology",
  "New Horizon College of Engineering",
  "Nirmal Jyothi Technical Institute",
  "Nitte Institute of Technology",
  "Nitte School of Architecture",
  "NITTE School of Fashion Technology & Interior",
  "Palotti College",
  "P E S School of Engineering",
  "PES Institute of Technology",
  "PES University",
  "PESIT South Campus",
  "PNS Womens Institute of Technology",
  "Presidency College, Hebbal",
  "Presidency University",
  "RajaRajesheshwari College of Engineering",
  "Rajiv Gandhi Institute of Technology",
  "Rajalakshmi Engineering College",
  "Reva University (School of CSE)",
  "RCD College of Management and Information Technology",
  "Ramaiah Institute of Technology",
  "Reva Institute of Engineering & Technology",
  "Reva Institute of Science & Technology",
  "RL Jalappa Institute of Technology",
  "RNS Institute of Technology",
  "RR Institute of Technology",
  "RR School of Architecture",
  "RV College of Architecture",
  "RV College of Engineering",
  "RVD College of Management & Information Tec",
  "Sai Vidya Institute of Technology",
  "Sambhram Institute of Technology",
  "Sambhram Academy of Management Studies, Hesaraghatta Road",
  "Sapthagiri College of Engineering (Bagalagunte)",
  "Seshadripuram College",
  "SCT Institute of Technology",
  "SEA College of Engineering & Technology",
  "Sree Sankaracharya University of Sanskrit",
  "Sree Saraswathi Thyagaraja College",
  "Sri Bhagwan Mahavir Jain College",
  "Sri Sai Ram Engineering College",
  "St. Anne's Degree College for Women",
  "St. Aloysius College",
  "Shri Pillappa College of Engineering",
  "Shri Vidya Vinaya Institute Of Technology",
  "Sir M Visvesvaraya Institute of Technology (Hun",
  "SJB Institute of Technology",
  "SJB School of Architecture & Planning",
  "SJC Institute of Technology",
  "Sri Krishana Institute of Technology",
  "Sri Revana Siddeshwara Institute of Technology",
  "Sri Sairam College of Engineering",
  "Sri Venkataraju Institute of Tech",
  "Sri Venkateshwara College of Engineering",
  "Sri Vidya Vinayaka Institute of Technology (Vin",
  "St. Claret",
  "St. Francis, Kormangala",
  "St. George College of Management",
  "St. Joseph's University",
  "St. Joseph's College (Autonomous), Langford Town, Bangalore",
  "T John Institute of Technology",
  "The Oxford College of Engineering",
  "The Oxford College of Science",
  "United International College",
  "Vidyashilp Academy",
  "Vijaya College",
  "Vivekananda College of Arts, Science, and Commerce",
  "University Vishweshwaraya College of Engineeri",
  "Vemana Institute of Technology",
  "Vijaya Vittal Institute of Technology",
  "Vishveshwaraiah Technological University",
  "Vivekananda Institute of Technology",
  "VTU Extension Center (BMS College of Engine",
  "VTU Extension Center (Karnataka State Remot",
  "VTU Extension Centre (IR Rasta)",
  "VTU Extension Centre (United Technologies L",
  "VTU Extension centre (Reva Institute of Techno",
  "Yellamma Dasappa Institute of Technology",
];

export default collegeOptions;
