const collegeOptions = [
  "Acharya Institute of Technology",
  "Acharya Pathashala Rural College of Engineering",
  "Acharyas NRV School of Architecture (Soladeva",
  "Achutha Institute of Technology",
  "ACS College of Engineering",
  "Aditya Academy of Architecture & Design",
  "Alliance College of engineering and design (Chik",
  "Alpha College of Engineering",
  "AMC College of Engineering",
  "Amrita School of Engineering",
  "Amrutha Institute of Engineering & Management",
  "Atria Institute of Technology",
  "Bangalore College of Engineering & Tech",
  "Bangalore Institute of Technology",
  "Bangalore Technological Institute",
  "BES Institute of Technology",
  "BMS College of Architecture",
  "BMS College of Engineering",
  "BMS Institute of Technology",
  "BMS School of Architecture",
  "BNM Institute of Technology",
  "Brindavan College of Engineering",
  "BSF Institute of Technology",
  "BTL Institute of Technology Management",
  "Cambridge Institute of Technology",
  "Cambridge Institute of Technology (North Camp",
  "CES Institute of Fashion Technology",
  "Christ (Deemed to be University) Central campus",
  "Christ (Deemed to be University) Lavasa, Pune",
  "Christ Deemed to be University (Kengeri)",
  "City Engineering College",
  "CMR institute of Technology",
  "CMR University OMBR Campus",
  "Dayananda Sagar Academy of Technology & Ma",
  "Dayananda Sagar College of Engineering",
  "Dayananda Sagar Institute of Technology",
  "Don Bosco Institute of Technology",
  "Dr Ambedkar Institute of Technology",
  "Dr Sri Sri Sri Shivakumara Mahaswamy College",
  "East Point College of Engineering & Technology",
  "East Point College of Engineering for Women",
  "East West College of Engineering",
  "East West Institute of Technology",
  "East West Polytechnic",
  "Ghousia College of Engineering",
  "Global Academy of Technology",
  "Gopalan College of Engineering & Management",
  "Gopalan School of Architecture & Planning",
  "Government Engineering College (Ramanagara)",
  "Government SKSJ Technological Institute (K R",
  "HKBK College of Engineering",
  "Impact College of Engg & Applied Science",
  "Impact School of Architecture",
  "Indian Academy School of Management Studies",
  "Indian Institute of Science (IISc)",
  "Islamia Niswan Degree College for Women",
  "Islamiah Institute of Technology",
  "Jain University (Jakkasandra)",
  "Jain University Jayanagar",
  "Jnana Vikas Institute of Technology",
  "JSS Academy of Technical Education",
  "Jyoti Nivas",
  "Jyothy Institute of Technology",
  "KNS Institute of Technology",
  "KS Institute of Technology",
  "KS School of Engineering and Management (KS",
  "MN Technology Institutute",
  "Mangalore Institute of Fire & Safety Engineering",
  "Mount Carmel College",
  "MS Engineering College",
  "MS Ramaiah Institute of Technology",
  "M S Ramaiah Institute of Technology",
  "MVJ College of Engineering",
  "Nadgir Institute of Engineering & Technology",
  "Nagarjuna College of Engineering & Technology",
  "New Horizon College of Engineering",
  "Nirmal Jyothi Technical Institute",
  "Nitte Institute of Technology",
  "Nitte School of Architecture",
  "NITTE School of Fashion Technology & Interior",
  "P E S School of Engineering",
  "PES Institute of Technology",
  "PES University",
  "PESIT South Campus",
  "PNS Womens Institute of Technology",
  "Presidency College, Hebbal",
  "Presidency University",
  "RajaRajesheshwari College of Engineering",
  "Rajiv Gandhi Institute of Technology",
  "RCD College of Management and Information Technology",
  "Reva Institute of Engineering & Technology",
  "Reva Institute of Science & Technology",
  "RL Jalappa Institute of Technology",
  "RNS Institute of Technology",
  "RR Institute of Technology",
  "RR School of Architecture",
  "RV College of Architecture",
  "RV College of Engineering",
  "RVD College of Management & Information Tec",
  "Sai Vidya Institute of Technology",
  "Sambhram Institute of Technology",
  "Sapthagiri College of Engineering (Bagalagunte)",
  "SCT Institute of Technology",
  "SEA College of Engineering & Technology",
  "Shri Pillappa College of Engineering",
  "Shri Vidya Vinaya Institute Of Technology",
  "Sir M Visvesvaraya Institute of Technology (Hun",
  "SJB Institute of Technology",
  "SJB School of Architecture & Planning",
  "SJC Institute of Technology",
  "Sri Krishana Institute of Technology",
  "Sri Revana Siddeshwara Institute of Technology",
  "Sri Sairam College of Engineering",
  "Sri Venkataraju Institute of Tech",
  "Sri Venkateshwara College of Engineering",
  "Sri Vidya Vinayaka Institute of Technology (Vin",
  "St. Claret",
  "St. Francis, Kormangala",
  "T John Institute of Technology",
  "The Oxford College of Engineering",
  "University Vishweshwaraya College of Engineeri",
  "Vemana Institute of Technology",
  "Vijaya Vittal Institute of Technology",
  "Vishveshwaraiah Technological University",
  "Vivekananda Institute of Technology",
  "VTU Extension Center (BMS College of Engine",
  "VTU Extension Center (Karnataka State Remot",
  "VTU Extension Centre (IR Rasta)",
  "VTU Extension Centre (United Technologies L",
  "VTU Extension centre (Reva Institute of Techno",
  "Yellamma Dasappa Institute of Technology"
];

export default collegeOptions;
